
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `TB_MEMBERSHIPCARD`
-- ----------------------------
DROP TABLE IF EXISTS `TB_MEMBERSHIPCARD`;
CREATE TABLE `TB_MEMBERSHIPCARD` (
 		`MEMBERSHIPCARD_ID` varchar(100) NOT NULL,
		`DISCOUNT` varchar(255) DEFAULT NULL COMMENT '折扣',
		`GOSTARTTIME` varchar(255) DEFAULT NULL COMMENT '领取开始时间',
		`GOENDTIME` varchar(255) DEFAULT NULL COMMENT '领取截至时间',
		`USESTARTTIME` varchar(255) DEFAULT NULL COMMENT '使用开始时间',
		`USEENDTIME` varchar(255) DEFAULT NULL COMMENT '使用截至时间',
		`NUMBER` varchar(255) DEFAULT NULL COMMENT '数量',
		`CREATETIME` varchar(255) DEFAULT NULL COMMENT '创建会员卡时间',
  		PRIMARY KEY (`MEMBERSHIPCARD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
