-- ----------------------------
-- Table structure for "C##NEWO"."TB_MEMBERSHIPCARD"
-- ----------------------------
-- DROP TABLE "C##NEWO"."TB_MEMBERSHIPCARD";
CREATE TABLE "C##NEWO"."TB_MEMBERSHIPCARD" (
	"DISCOUNT" VARCHAR2(255 BYTE) NULL ,
	"GOSTARTTIME" VARCHAR2(255 BYTE) NULL ,
	"GOENDTIME" VARCHAR2(255 BYTE) NULL ,
	"USESTARTTIME" VARCHAR2(255 BYTE) NULL ,
	"USEENDTIME" VARCHAR2(255 BYTE) NULL ,
	"NUMBER" VARCHAR2(255 BYTE) NULL ,
	"CREATETIME" VARCHAR2(255 BYTE) NULL ,
	"MEMBERSHIPCARD_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."DISCOUNT" IS '折扣';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."GOSTARTTIME" IS '领取开始时间';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."GOENDTIME" IS '领取截至时间';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."USESTARTTIME" IS '使用开始时间';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."USEENDTIME" IS '使用截至时间';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."NUMBER" IS '数量';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."CREATETIME" IS '创建会员卡时间';
COMMENT ON COLUMN "C##NEWO"."TB_MEMBERSHIPCARD"."MEMBERSHIPCARD_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table TB_MEMBERSHIPCARD
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##NEWO"."TB_MEMBERSHIPCARD"

-- ----------------------------

ALTER TABLE "C##NEWO"."TB_MEMBERSHIPCARD" ADD CHECK ("MEMBERSHIPCARD_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##NEWO"."TB_MEMBERSHIPCARD"
-- ----------------------------
ALTER TABLE "C##NEWO"."TB_MEMBERSHIPCARD" ADD PRIMARY KEY ("MEMBERSHIPCARD_ID");
